import Head from 'next/head'

import { Inter } from '@next/font/google'

import {useState} from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home()
{
    const [count,setCount]=useState(0)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
          </Head>
          <main>
              <h1>counter :{count} with next.js on github and vercel</h1>
              <br />
              <button onClick={()=>setCount(count+1)}>+</button>
              <button onClick={()=>setCount(count-1)}>-</button>
      </main>
    </>
  )
}
